version: '3.8'
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./server:/usr/src/app
    command: npm run start:prod

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3050:80"
    depends_on:
      - backend
